### ISSUE TITLE
Error: Call to undefined function drush_config_get_storage_filters() in drush_drush_cmi_tools_config_import_plus()

### ISSUE THREAD

**Issue by jiisuominen** [previousnext/drush_cmi_tools#13] opened 2017-04-28 06:39 UTC
Hey!

Since updating to Drupal 8.3.1, I started to get this error when trying to run drush cimy.

From these lines:
` 
  $storage_filters = drush_config_get_storage_filters();
  if (!empty($storage_filters)) {
    $source_storage = new StorageWrapper($source_storage, $storage_filters);
  }
`

In config_ignore they just removed exactly the same lines than we have here: https://www.drupal.org/node/2867447

If I remove these lines, no ignore files are respected.

I have drush version 8.1.11

This is only issue left for me to be able to update core to 8.3.1 so any help is appreciated.

Cheers,
Janne

**Comment by larowlan** [comment] 2017-05-01 20:55
Fixed by #14, change was caused by latest version of drush removing that function

**Closed as completed by larowlan** 2017-05-01 20:55 UTC
